import type { Metadata } from "next";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Jomhuria } from 'next/font/google'
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import "./globals.css";
config.autoAddCss = false;
const jomhuria = Jomhuria({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <GoogleOAuthProvider clientId="717208055945-s60n7eev35fbuvpma1cdpvru5j83fose.apps.googleusercontent.com">
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
